name: Pipeline
on: [push]
env:
  APPLICATION_NAME: startupapp
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python Environment
        uses: actions/setup-python@v1.1.1
      - name: Install Requirements
        run: pip install --quiet --requirement requirements.txt
      - name: Lint Code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 test_app.py
      - name: Run UnitTest
        run: |
          python -m unittest --verbose --failfast
          
