name: Pipeline
on: [push]
env:
  APPLICATION_NAME: startupapp
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python Environment
        uses: actions/setup-python@v1.1.1
      - name: Install Requirements
        run: pip install --quiet --requirement requirements.txt
      - name: Run UnitTest
        run: |
          python -m unittest --verbose --failfast
          
